Write-Host "Uninstalling Git..."
winget uninstall --id "Git.Git"
Write-Host "Uninstalling GitHub CLI..."
winget uninstall --id "GitHub.cli"
Write-Host "Uninstalling Starship..."
winget uninstall --id "Starship.Starship"
Write-Host "Uninstalling Jetbrains Toolbox..."
winget uninstall --id "JetBrains.Toolbox"